username: <username/email>
password: <password>
maxRetries: 6
delayBetweenRetries: 5000
jobs:
    - jobType: stock_screener
      outDir: "./output/stockScreener"
      parameters:
          - id: zacks_rank
            value: "1"
            operator: ">="
          - id: value_score
            value: "A"
            operator: ">="
          - id: momentum_score
            value: "A"
            operator: ">="
    - jobType: esp_filter
      outDir: "./output/espFilter"
      parameters:
          - filter_type: "buys"
          - esp_checkboxes: [1]
          - zacks_rank_checkboxes: []
          - surp_checkboxes: []
          - reporting_date_checkboxes: []
